removed superfluous whitespaces
kiegroup/kie-jenkins-scripts pull request #1033
Opened 2021-07-13 11:08 UTC by mbiarnes

**Thank you for submitting this pull request**

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2021-07-13 12:56 UTC, mbiarnes commented
The aditional test was failing for community releases but nor for daily buils.
Main difference, there was an mvn execution that was removed so tis test is synced with the test in daily builds.

2021-07-13 14:31 UTC, mareknovotny approved these changes

2021-07-15 09:05 UTC, winklerm requested changes
One minor issue, otherwise looks ok to me.

2021-07-15 09:05 UTC, winklerm commented on job-dsls/jobs/kie/master/communityRelease_pipeline.groovy
> +    label('kie-rhel7&&kie-mem8g&&!master')
This is for specification where the matrix parent job can run, I think you do not need to restrict it to `kie-mem8g`.

2021-07-19 09:36 UTC, merged