BXMSPROD-1084: changed execution command
kiegroup/kie-jenkins-scripts pull request #858
Opened 2020-11-09 15:23 UTC by mbiarnes

**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[BXMSPROD-1084](https://issues.redhat.com/browse/BXMSPROD-1084)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* referenced pull request 1
* referenced pull request 2
* referenced pull request 2
etc. 

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2020-11-09 15:27 UTC, Kaitou786 requested changes
Please see other occurrences

2020-11-09 15:27 UTC, Kaitou786 commented on job-dsls/jobs/communityRelease_pipeline.groovy
> +                sh "./ droolsjbpm-build-bootstrap/script/release/eraseM2.sh $m2Dir"
For the executable to run, there should be no space between `./` and the file.

2020-11-09 15:58 UTC, mbiarnes commented
replaced sh './droolsjbpm-build-bootstrap/... everywhere where before was used sh 'sh droolsjbpm-build-bootstrap/...

2020-11-09 16:18 UTC, Kaitou786 approved these changes
lgtm

2020-11-10 08:22 UTC, mareknovotny approved these changes

2020-11-10 08:23 UTC, merged