replaced origin-repositories.jboss.org
kiegroup/kie-jenkins-scripts pull request #956
Opened 2021-04-01 08:19 UTC by mbiarnes

**Thank you for submitting this pull request**
 
- replaces the `original-repositories.jboss.org/` URL by `repositories.jboss.org/`
The problem was, that somehow the `repositories.jboss.org` only get updated if there was before a request for certain artifacs.
i.e.: when the artifacts are uploaded to a staging repository for sanity checks these are not visible in `repositories.jboss.org` until there is a request for an artifact. Before i.e. https://repository.jboss.org/nexus/content/groups/kie-group/org/kie/business-central/7.52.0.Final is loaded and accessible the has to be before a request for i.e. https://repository.jboss.org/nexus/content/groups/kie-group/org/kie/business-central/7.52.0.Final/business-central-7.52.0.Final-wildfly-deployable.zip.
Once an artifact is requested the directory gets loaded.
Thus we used before `original-repositories.jboss.org` because there we didn't had this problem, but we were advised to please not use `original-repositories` any more.

- pre-loads some directories in repository.jboss.org so people can access for sanity checks and when they want do download artifacts after the release is closed

<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2021-04-01 11:47 UTC, mbiarnes commented
Please don't merge yet - still working on this

2021-04-06 07:43 UTC, winklerm requested changes
Please fix the typo, otherwise ok!

From my POV, it would be nice to have the list of URLs defined at one place so future changes will be less error-prone. For instance, after the `wildfly19` suffix changes with a new version. But it is not a blocker for merging this PR.

2021-04-06 07:43 UTC, winklerm commented on job-dsls/jobs/kie/master/communityRelease_pipeline.groovy
>                  'You can download the artefacts..: \\n' +
A minor typo:
```suggestion
                'You can download the artifacts..: \\n' +
```

2021-04-06 09:47 UTC, mareknovotny approved these changes

2021-04-19 10:40 UTC, merged