added Ant neded for creation of jbpm-installers
kiegroup/kie-jenkins-scripts pull request #966
Opened 2021-04-27 10:32 UTC by mbiarnes

**Thank you for submitting this pull request**

Ant installation needed for creation of jbpm-installers during the community pipeline
<pre>
How to retest a PR or trigger a specific build:

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
</pre>

2021-04-27 10:44 UTC, winklerm requested changes
Looks ok, except the spaces inside {{ and }} for variables - that I think is a convention (not sure if a requirement) by Ansible.

2021-04-27 10:44 UTC, winklerm commented on jenkins-slaves/ansible/roles/common/tasks/main.yml
> +    url: https://archive.apache.org/dist/ant/binaries/apache-ant-{{ant_version}}-bin.tar.gz
I think the spaces inside {{ and }} should be preserved:
```suggestion
    url: https://archive.apache.org/dist/ant/binaries/apache-ant-{{ ant_version }}-bin.tar.gz
```

2021-04-27 10:44 UTC, winklerm commented on jenkins-slaves/ansible/roles/common/tasks/main.yml
> +    src: /tmp/downloads/apache-ant-{{ant_version}}-bin.tar.gz
The same here:
```suggestion
    src: /tmp/downloads/apache-ant-{{ ant_version }}-bin.tar.gz
```

2021-04-27 12:14 UTC, mareknovotny commented
just curious why or what do we need ant for?

2021-05-03 07:32 UTC, mbiarnes commented
@mareknovotny Ant is needed for the creation of the jbpm-installers when a community release was done

2021-05-03 07:35 UTC, winklerm approved these changes
LGTM, thanks!

2021-05-03 07:46 UTC, merged